"""Native Windows four-batch controller for an independently sealed study.

No RNG/inputs are generated by run/resume. Ended interruptions may be retained;
only one explicit posterior infrastructure retry is permitted by the runtime.
Native acceptance evidence is required; its producer is a separate finite run.
"""
import argparse
import json
import os
from pathlib import Path
import sys
import time
import traceback
import uuid

ROOT=Path(__file__).resolve().parents[2]
sys.path[:0]=[str(ROOT/'scripts/completion'),str(ROOT/'scripts/windows')]
from formal_runtime import atomic_json,file_hash,fingerprint,host_lease,ResourceWait
from formal_freeze import verify_sealed_study,relative_file
from formal_execution import StudyDispatch,ENDED
from formal_acceptance import verify_native_acceptance
from task_journal import read_task_export,TaskJournal


def verify_phase_closure(directory, dispatch, batch, phase):
    """Verify the recorded closed frame, not current liveness of another Job."""
    directory=Path(directory)
    pointer=json.loads((directory/'latest-closed.json').read_text())
    summary_file=relative_file(directory,pointer['summary'])
    if file_hash(summary_file)!=pointer['sha256']:raise ValueError('Prior closed phase changed')
    report=json.loads(summary_file.read_text());rows=[]
    for name,digest in report['rows'].items():
        path=relative_file(summary_file.parent,name)
        if file_hash(path)!=digest:raise ValueError('Prior phase row changed')
        row=json.loads(path.read_text())
        export=relative_file(summary_file.parent,row['history_export'])
        if file_hash(export)!=row['history_export_sha256']:raise ValueError('Prior history export changed')
        history=read_task_export(export)['entry']
        if history['task']!=row['task'] or history['attempts'][-1]['outcome']!=row['outcome']:
            raise ValueError('Prior phase row and task history differ')
        rows.append(row)
    expected=dispatch.summarize_phase(batch,phase,rows)
    if report['summary']!=expected or expected['closed'] is not True:
        raise ValueError('Earlier batch/phase is incomplete')
    return pointer


def run(bundle,host_lock,rscript,r_library,native_acceptance,batch,phase,*,resume=False,retry_task=None,retry_reason=None):
    if sys.platform!='win32':raise ValueError('Actual native Windows required for formal execution')
    if bool(retry_task)!=bool(retry_reason) or (retry_task and (not resume or phase!='main')):
        raise ValueError('One named posterior retry needs explicit resume and a recorded reason')
    bundle,host_lock,rscript,r_library,native_acceptance=map(lambda p:Path(p).resolve(),
        (bundle,host_lock,rscript,r_library,native_acceptance))
    # A study-level driver lease prevents competing phase writers. The shared
    # host lease remains owned per actual runtime call, including every child.
    with host_lease(bundle/'formal-driver.lock','formal phase driver'):
        invocation=bundle/'driver-invocations'/uuid.uuid4().hex
        invocation.mkdir(parents=True,exist_ok=False)
        began=time.perf_counter()
        atomic_json(invocation/'started.json',dict(batch=batch,phase=phase,resume=resume,retry_task=retry_task,
            retry_reason=retry_reason,started_ns=time.time_ns(),timestamp_is_not_duration=True,
            source_sha256=file_hash(__file__),pid=os.getpid(),
            cost_scope='Controller body from preflight through its closing report; interpreter import/startup, final report write and between-invocation waiting excluded. Includes nested task calls; do not add them again.'))
        rows=[];new=0;visited=0
        try:
            marker,p=verify_sealed_study(bundle)
            design=json.loads((bundle/'study-plan.json').read_text())
            catalog=json.loads((bundle/'catalog.json').read_text())
            descriptor=json.loads((bundle/'archive.json').read_text())
            bound=descriptor['binding'];env=bound['environment']
            if str(host_lock)!=bound['shared_host_lock'] or str(rscript)!=env['rscript'] or str(r_library)!=env['r_library']:
                raise ValueError('Frozen host lease or R environment path differs')
            # Full canonical source and dependency binding, including Python,
            # device identity and old venv marker; volatile resource samples are
            # recorded by the original freeze and runtime separately.
            from prepare_formal_study import gather_environment
            current,probe,resources,_,_=gather_environment(rscript,r_library)
            atomic_json(invocation/'environment-probe.json',probe)
            atomic_json(invocation/'resources.json',resources)
            if current!=env:raise ValueError('Frozen native Python/R/device environment changed')
            for name,digest in p['source_files'].items():
                if file_hash(ROOT/name)!=digest:raise ValueError('Frozen source changed: '+name)
            verify_native_acceptance(native_acceptance,p,ROOT,environment=env)
            dispatch=StudyDispatch(p,design['cache_allocation'],catalog)
            phase_root=bundle/'formal-runs'/f'batch-{batch:02d}'/phase
            earlier={}
            for b,previous in dispatch.predecessors(batch,phase):
                earlier[f'{b}:{previous}']=verify_phase_closure(bundle/'formal-runs'/f'batch-{b:02d}'/previous,dispatch,b,previous)
            atomic_json(invocation/'predecessors.json',earlier)
            phase_root.mkdir(parents=True,exist_ok=True)
            identifiers = {t['id'] for t in dispatch.tasks(batch,phase)}
            planned = len(identifiers)
            if retry_task and retry_task not in identifiers:
                raise ValueError('Retry task is not in this frozen main batch')
            from formal_owned_runtime import Coordinator
            from formal_measured_runtime import invoke
            import psutil
            coordinator=Coordinator(host_lock)
            registered=set(coordinator.task_keys(p['protocol_sha256'],batch))
            run_folder=phase_root/'visits'/invocation.name;run_folder.mkdir(parents=True,exist_ok=False)
            for index,slot in enumerate(dispatch.slots(batch,phase)):
                task=slot['task'];identifier=task['id']
                request=dispatch.request(slot,bundle=bundle,source_root=ROOT,rscript=rscript,r_library=r_library,
                                         sealed_marker=bundle/'FROZEN.json',native_acceptance=native_acceptance)
                kwargs=dict(task=task,request=request,worker=ROOT/'scripts/windows'/(
                    'formal_batch_worker.py' if phase=='main' else 'formal_cache_worker.py'),
                    output=phase_root/'tasks'/identifier,limits=p['windows_limits'])
                print(json.dumps(dict(index=index+1,total=planned,task=task)),flush=True)
                if psutil.virtual_memory().available<p['minimum_available_ram_bytes']:
                    raise ResourceWait('Host available RAM refused at task boundary; remaining slots stay unvisited')
                key=TaskJournal.key(task)
                result=invoke(coordinator,kwargs,phase_root/'call-costs'/identifier,
                              resume=resume and key in registered,retry=retry_task==identifier)
                registered.add(key)
                export=run_folder/(identifier+'.history.json')
                coordinator.export_task(task,export)
                row=dict(task=task,scheduled_index=index+1,outcome=result['outcome'],newly_executed=result['newly_executed'],
                         samples_eligible=result['samples_eligible'],measurement_available=result['measurement_available'],
                         history_export=export.name,history_export_sha256=file_hash(export))
                if row['outcome'] not in ENDED:raise ValueError('Runtime returned a non-ended task')
                destination=run_folder/(identifier+'.json');atomic_json(destination,row)
                rows.append(row);new+=int(row['newly_executed']);visited+=1
                # Constant-sized progress only; do not rewrite all earlier rows.
                atomic_json(phase_root/'progress.json',dict(invocation=invocation.name,planned=planned,
                    visited=visited,newly_executed=new,last_task=identifier,last_outcome=row['outcome'],
                    not_a_closed_phase_or_liveness_proof=True))
                print(json.dumps(dict(task=identifier,outcome=row['outcome'],newly_executed=row['newly_executed'])),flush=True)
            summary=dispatch.summarize_phase(batch,phase,rows)
            if not summary['closed']:raise ValueError('Cannot close an incomplete phase')
            closure=dict(summary=summary,rows={r['task']['id']+'.json':file_hash(run_folder/(r['task']['id']+'.json')) for r in rows},
                         phase_closure_does_not_imply_convergence=True)
            atomic_json(run_folder/'closed.json',closure)
            atomic_json(phase_root/'latest-closed.json',dict(summary=(run_folder/'closed.json').relative_to(phase_root).as_posix(),
                                                          sha256=file_hash(run_folder/'closed.json')))
            result=dict(summary,controller_seconds=time.perf_counter()-began,newly_executed=new,
                        invocation=str(invocation),formal_inference_complete=False)
            atomic_json(invocation/'finished.json',result)
            return result
        except BaseException as exc:
            atomic_json(invocation/'failed.json',dict(error=type(exc).__name__+': '+str(exc),
                traceback=traceback.format_exc(),controller_seconds=time.perf_counter()-began,
                visited=visited,newly_executed=new,failure_is_not_a_numerical_task_result=True,
                automatic_retries=False,unvisited_tasks_are_not_failures=True))
            raise


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    for name in ('bundle','host-lock','rscript','r-library','native-acceptance'):
        parser.add_argument('--'+name,type=Path,required=True)
    parser.add_argument('--batch',type=int,choices=range(4),required=True)
    parser.add_argument('--phase',choices=['main','cache'],required=True)
    parser.add_argument('--resume',action='store_true');parser.add_argument('--retry-task');parser.add_argument('--retry-reason')
    print(json.dumps(run(**vars(parser.parse_args())),indent=2),flush=True)
