"""Freeze and persist only 27 native Windows technical fits plus 24 probes.

This is an explicitly bounded engineering gate, never the 41,472 formal grid.
Protocol generation and sampling are separate commands and commits. No inputs
are generated by run/resume, and cache selection does not inspect main results.
"""
import argparse
import copy
import importlib.metadata
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time

ROOT=Path(__file__).resolve().parents[2]
sys.path[:0]=[str(ROOT/'scripts/windows'),str(ROOT/'scripts/completion'),str(ROOT/'r-package/inst/python'),str(ROOT/'examples')]
from formal_runtime import atomic_json,file_hash,fingerprint,ResourceWait,ResumeConflict,HostBusy
from batch_contract import BatchPlan,create_tasks,WORKFLOWS
from owned_runtime import Coordinator
from measured_runtime import invoke


def sources():
    names=subprocess.check_output(['git','ls-files','r-package/inst/python','scripts/completion','scripts/windows','examples'],cwd=ROOT,text=True).splitlines()
    names=[n for n in names if n.endswith(('.py','.R')) and n!='scripts/windows/audit_technical_batch.py']
    names+=['benchmark/protocols/windows-native-v1.json','benchmark/protocols/inference-budget-pilot-mac-v1.json',
            'benchmark/analysis/outputs/completion-f3/reference-reuse.json',
            'benchmark/analysis/outputs/wells-quadrature-v1/R12-n96.json',
            'benchmark/analysis/outputs/wells-quadrature-v1/result.json']
    # Canonical raw source bytes are required, never a platform-modified hash.
    import hashlib
    result={}
    for name in sorted(set(names)):
        actual=file_hash(ROOT/name)
        blob=hashlib.sha256(subprocess.check_output(['git','show','HEAD:'+name],cwd=ROOT)).hexdigest()
        if actual!=blob:raise ValueError('Commit/canonical source bytes required before freeze: '+name)
        result[name]=actual
    if 'scripts/completion/cached_execution.py' not in result:raise ValueError('Prepared execution source must be explicit')
    return result


def freeze(output,rscript,r_library):
    if sys.platform!='win32':raise ValueError('Native Windows freeze required')
    output=Path(output).resolve()
    if output.exists():raise FileExistsError('New freeze directory required')
    if subprocess.check_output(['git','status','--porcelain'],cwd=ROOT,text=True).strip():raise ValueError('Commit source first')
    import numpy as np
    import psutil
    import torch
    from formal_inputs import build_payload,validate_addresses
    from mechanism_runner import actual_hash
    if not torch.cuda.is_available() or torch.cuda.get_device_capability()!=(12,0):raise ValueError('Actual RTX5080 CUDA required')
    environment=dict(os.environ,R_LIBS_USER=str(Path(r_library).resolve()))
    code='cat(jsonlite::toJSON(list(R=R.version.string,posterior=as.character(packageVersion("posterior"))),auto_unbox=TRUE))'
    renv=json.loads(subprocess.check_output([str(rscript),'--vanilla','-e',code],env=environment,text=True))
    catalog=json.loads((ROOT/'benchmark/protocols/inference-budget-pilot-mac-v1.json').read_text())
    identity='windows-batch-technical-v1'
    groups=[dict(models=['G1','L1'],replicates=[0],budgets=[64],workflows=list(WORKFLOWS)),
            dict(models=['G2'],replicates=[0],budgets=[16384],workflows=list(WORKFLOWS))]
    tasks=create_tasks(identity,groups)
    targets=[copy.deepcopy(t) for t in catalog['targets'] if t['name'] in ('G1','L1','G2')]
    device=torch.cuda.get_device_properties(0)
    resources=dict(ram_total=psutil.virtual_memory().total,ram_available=psutil.virtual_memory().available,
        disk=shutil.disk_usage(output.parent)._asdict(),gpu_name=device.name,gpu_total_bytes=device.total_memory,
        gpu_free_bytes=torch.cuda.mem_get_info()[0],architecture=list(torch.cuda.get_device_capability()),
        runtime_estimates_are_conservative_not_inference=True)
    limits=dict(rss_bytes=8*1024**3,job_commit_bytes=12*1024**3,disk_start_bytes=4*1024**3,
                disk_floor_bytes=1024**3,poll_seconds=.2)
    p=dict(schema=1,identity=identity,scope_kind='technical_batch_validation',required_platform='win32',
        batch_size=32,groups=groups,tasks=tasks,targets=targets,inputs={},source_files=sources(),
        source_commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),
        required_versions={n:importlib.metadata.version(n) for n in ('numpy','scipy','torch','pyro-ppl','psutil')},
        required_R_version=renv['R'],required_R_posterior=renv['posterior'],
        controls=dict(chains=4,mh_discard=512,nuts_warmup=1024,nuts_tree_depth=8,nuts_target_accept=.8,
            nuts_full_mass=False,nuts_workers=4,nuts_threads=1,torch_threads=4,window=32,quasi_deer_max_iter=2048,
            atol=1e-10,rtol=1e-10,memory_limit_mb=2048,maximum_member_bytes=128*1024**2,
            minimum_gpu_free_bytes=3*1024**3),
        process_tree_rss_limit_bytes=limits['rss_bytes'],required_disk_bytes_per_task=limits['disk_start_bytes'],
        windows_limits=limits,minimum_available_ram_bytes=12*1024**3,resources_at_freeze=resources,
        cost_policy=dict(primary='Ordinary subprocess through exit, then independent audit; external invocation separately measured',
            cached='Separate 24 probes, one initial plus three prepared executions; not hidden in main fits',
            verification='Extra terminal checks separate; missing clocks remain unknown',nested_phases_additive=False),
        recovery_policy='At most one explicit posterior infrastructure retry after kernel job end proof; no cache retry',
        native_runtime_schema='windows-owned-runtime-v1',no_total_time_cutoff=True,
        pair_atol=1e-7,pair_rtol=1e-7,
        scientific_scope='One technical input per model, descriptive costs only, no repeat confidence intervals',
        formal_inference_complete=False,formal_scientific_repetitions=0)
    # Three master files generated once, before any sampling, in a new namespace.
    output.mkdir();(output/'inputs').mkdir()
    p['addresses']=validate_addresses(identity,[t['name'] for t in targets],[0],4)
    for item in targets:
        n=max(t['budget'] for t in tasks if t['model']==item['name'])+512
        data=build_payload(identity,item['name'],0,item['dimension'],n,4)
        name=item['name']+'-rep0000.npz';np.savez_compressed(output/'inputs'/name,**data)
        p['inputs'][name]=dict(model=item['name'],replicate=0,dimension=item['dimension'],chains=4,steps=n,
            sha256=file_hash(output/'inputs'/name),actual_sha256=actual_hash(data))
        del data
    p['protocol_sha256']=fingerprint(p);BatchPlan(p);atomic_json(output/'protocol.json',p)
    # Separate cache identity, frozen before main results, reuses identical files.
    from formal_measurement_plan import create_measurement_plan
    cache=copy.deepcopy(p);cache.pop('protocol_sha256');cache['identity']='windows-owned-cache-technical-v1'
    cache['groups']=[dict(g,workflows=[w for w in g['workflows'] if 'nuts' not in w]) for g in groups]
    cache['tasks']=create_tasks(cache['identity'],cache['groups'])
    cache['source_primary_protocol_sha256']=p['protocol_sha256'];cache['new_independent_inputs']=0
    cache['source_primary_task_ids']={t['id']:next(a['id'] for a in tasks if all(t[k]==a[k] for k in ('model','workflow','budget','replicate'))) for t in cache['tasks']}
    allocation=create_measurement_plan(cache['identity'],cache['tasks'])
    cache['cache_allocation_sha256']=allocation['allocation_sha256']
    cache['protocol_sha256']=fingerprint(cache);BatchPlan(cache)
    atomic_json(output/'cache-protocol.json',cache);atomic_json(output/'cache-allocation.json',allocation)
    atomic_json(output/'freeze-environment.json',dict(resources=resources,python=sys.version,
        executable=sys.executable,packages={d.metadata['Name']:d.version for d in importlib.metadata.distributions()},
        driver=subprocess.check_output(['nvidia-smi'],text=True),source_commit=p['source_commit']))
    lock=subprocess.check_output([sys.executable,'-m','pip','freeze','--all'],text=True)
    (output/'pip-freeze.txt').write_text(lock,encoding='utf-8')
    check=subprocess.run([sys.executable,'-m','pip','check'],capture_output=True,text=True)
    (output/'pip-check.txt').write_text(check.stdout+check.stderr,encoding='utf-8')
    if check.returncode:raise ValueError('Frozen environment pip check failed; preserve partial freeze')
    # Preserve the original frozen venv byte-for-byte; bind it from this bundle.
    marker=output/'PARALLELBAYES-FROZEN.json'
    atomic_json(marker,dict(protocols=[p['protocol_sha256'],cache['protocol_sha256']],source_commit=p['source_commit'],
        dependency_sha256=file_hash(output/'pip-freeze.txt'),original_marker_sha256=file_hash(Path(sys.executable).parent.parent/'PARALLELBAYES-FROZEN.json')))
    (output/'source').mkdir()
    for name in p['source_files']:
        destination=output/'source'/name;destination.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(ROOT/name,destination)
    return dict(main_tasks=len(tasks),cache_tasks=len(cache['tasks']),main=p['protocol_sha256'],cache=cache['protocol_sha256'],source_commit=p['source_commit'])


def run(bundle,host_lock,rscript,r_library,phase,resume=False,retry_task=None):
    bundle=Path(bundle).resolve();p=json.loads((bundle/('protocol.json' if phase=='main' else 'cache-protocol.json')).read_text())
    plan=BatchPlan(p);tasks=list(plan.tasks())
    if sys.platform!='win32' or p['required_platform']!='win32' or p['scope_kind']!='technical_batch_validation' or len(tasks)!=(27 if phase=='main' else 24):
        raise ValueError('Only the bounded native Windows engineering plan may run')
    if p['identity']!=('windows-batch-technical-v1' if phase=='main' else 'windows-owned-cache-technical-v1'):
        raise ValueError('Formal launch is not authorized by this entry')
    for name,h in p['source_files'].items():
        if file_hash(ROOT/name)!=h:raise ResumeConflict('Frozen source changed: '+name)
    for name,row in p['inputs'].items():
        if file_hash(bundle/'inputs'/name)!=row['sha256']:raise ResumeConflict('Frozen actual input changed')
    c=Coordinator(host_lock);runroot=bundle/phase;runroot.mkdir(exist_ok=True)
    invocations=runroot/'invocations';invocations.mkdir(exist_ok=True)
    ordinal=len(list(invocations.glob('call-*')));call=invocations/f'call-{ordinal:04d}';call.mkdir()
    atomic_json(call/'started.json',dict(phase=phase,protocol_sha256=p['protocol_sha256'],resume=resume,retry_task=retry_task,started_ns=time.time_ns(),clock_not_duration=True))
    allocation=json.loads((bundle/'cache-allocation.json').read_text()) if phase=='cache' else None
    probes={v['primary_task_id']:v for v in allocation['probes']} if allocation else {}
    reports=[];new=0;start=time.perf_counter()
    for index,task in enumerate(tasks):
        capsule,h=plan.capsule(task['id'])
        request=dict(capsule=capsule,capsule_sha256=h,inputs=str(bundle/'inputs'),rscript=str(Path(rscript).resolve()),
            r_library=str(Path(r_library).resolve()),native_runtime_schema=p['native_runtime_schema'],
            required_gpu_free_bytes=p['controls']['minimum_gpu_free_bytes'],
            input_files={str(bundle/'inputs'/task['input']):p['inputs'][task['input']]['sha256']},
            source_files={str(ROOT/name):digest for name,digest in p['source_files'].items()})
        if phase=='cache':request['probe']=probes[task['id']]
        owned_task=dict(task,protocol_sha256=plan.protocol_sha256,artifact_kind='posterior' if phase=='main' else 'cache_measurement')
        kwargs=dict(task=owned_task,request=request,worker=ROOT/'scripts/windows'/('batch_worker.py' if phase=='main' else 'cache_worker.py'),
                    output=runroot/'tasks'/task['id'],limits=p['windows_limits'])
        print(json.dumps(dict(index=index+1,total=len(tasks),task=task)),flush=True)
        error=None;result=None
        try:
            import psutil
            if psutil.virtual_memory().available<p['minimum_available_ram_bytes']:raise ResourceWait('Host available RAM below declared start margin')
            registered=fingerprint(dict(protocol=plan.protocol_sha256,id=task['id'])) in c._read()['tasks']
            result=invoke(c,kwargs,runroot/'call-costs'/task['id'],resume=resume and registered,retry=retry_task==task['id'])
            new+=int(result['newly_executed'])
            outcome=result['outcome']
        except (HostBusy,ResumeConflict,ResourceWait,FileExistsError) as exc:
            error=type(exc).__name__+': '+str(exc)
            # Registry remains authoritative; a refusal is not numerical failure.
            data=c._read();key=fingerprint(dict(protocol=plan.protocol_sha256,id=task['id']))
            attempts=data['tasks'].get(key,{}).get('attempts',[])
            outcome=attempts[-1]['outcome'] if attempts else 'not_run'
        row=dict(task=task,outcome=outcome,error=error,newly_executed=bool(result and result['newly_executed']),
                 samples_eligible=bool(result and result['samples_eligible']),measurement_available=bool(result and result['measurement_available']))
        atomic_json(call/('task-'+task['id']+'.json'),row);reports.append(row)
        atomic_json(runroot/'progress.json',dict(planned=len(tasks),visited=len(reports),newly_executed=new,rows=reports,
            counts={v:sum(r['outcome']==v for r in reports) for v in ('valid','measurement_available','numerical_failure','resource_failure','output_failure_unclassified','infrastructure_interruption','not_run','active')}))
        print(json.dumps(row),flush=True)
    atomic_json(call/'finished.json',dict(seconds=time.perf_counter()-start,newly_executed=new,rows=reports,
        batch_phase_scope='Driver including coordinator calls and progress journals; separate from ordinary/individual invocation walls'))
    c.snapshot(call/'registry-snapshot.json')
    return dict(newly_executed=new,planned=len(tasks),phase=phase,rows=reports)


if __name__=='__main__':
    p=argparse.ArgumentParser();s=p.add_subparsers(dest='command',required=True)
    f=s.add_parser('freeze');f.add_argument('--output',type=Path,required=True);f.add_argument('--rscript',type=Path,required=True);f.add_argument('--r-library',type=Path,required=True)
    r=s.add_parser('run');r.add_argument('--bundle',type=Path,required=True);r.add_argument('--host-lock',type=Path,required=True);r.add_argument('--rscript',type=Path,required=True);r.add_argument('--r-library',type=Path,required=True);r.add_argument('--phase',choices=['main','cache'],required=True);r.add_argument('--resume',action='store_true');r.add_argument('--retry-task')
    a=vars(p.parse_args());command=a.pop('command');print(json.dumps((freeze if command=='freeze' else run)(**a)),flush=True)
